from inventory.exceptions import CommonException


class UserExistsException(CommonException):
    pass

